#!/usr/bin/perl -w

use strict;

my ($mydir, $myname);
BEGIN {
    $0=~ /(.*?)([^\/]+)\z/s or die "?";
    ($mydir, $myname)=($1,$2);
}
use lib "$mydir/perllib";
use lib "$mydir/ftemplate/lib";
use lib "$mydir/lib";
use Chj::Ml2json::OutputJSON;

open OUT, ">example_config.pl";

my $val=
  +{
    jsonfields_top=>
    $Chj::Ml2json::OutputJSON::default_jsonfields_top,
    jsonfields_orig_headers=>
    $Chj::Ml2json::OutputJSON::default_jsonfields_orig_headers,
   };
#use Data::Dumper;
#my $str= Dumper($val);
#$str=~ s|.VAR..= |+|;

use JSON;
print OUT to_json ($val, {pretty=>1});
close OUT or die;

